version: '3.5'

services:
  payara:
    image: payara/server-full:5.2022.5-jdk11
    ports:
      - "5080:8080"
      - "5081:8181"
      - "5048:4848"
    restart: always
#    environment:
#      - AS_ADMIN_PASSWORD=
    volumes:
      - /tmp/payara-apps:/opt/payara/deployments
    networks:
      - sample-network

volumes:
  app_data:

networks:
  sample-network:
    name: sample_net
